# exp_folders is a list of paths to folders containing AP .csv files
# ap_config is the path to the AP config file that generated the campaign data
# dataset_path is the path to the output folder where the dataset will be saved

[[datasets]]
name = "Varying Data Length 1P3S"
exp_folders = "/Users/kaleem/PhD/Data/5PI/--_Data Length Impact/Varying_Data_Length_1P3S"
ap_config = ""
dataset_path = "/Users/kaleem/PhD/Datasets/5PI/Varying_Data_Length_1P3S"

[[datasets]]
name = "Increasing Load 1P1S"
exp_folders = "/Users/kaleem/PhD/Data/5PI/--_Increasing Load/Increasing_Load_1P1S"
ap_config = ""
dataset_path = "/Users/kaleem/PhD/Datasets/5PI/Increasing_Load_1P1S"

[[datasets]]
name = "Increasing Load 1P2S"
exp_folders = "/Users/kaleem/PhD/Data/5PI/--_Increasing Load/Increasing_Load_1P2S"
ap_config = ""
dataset_path = "/Users/kaleem/PhD/Datasets/5PI/Increasing_Load_1P2S"

[[datasets]]
name = "Increasing Load 1P3S"
exp_folders = "/Users/kaleem/PhD/Data/5PI/--_Increasing Load/Increasing_Load_1P3S"
ap_config = ""
dataset_path = "/Users/kaleem/PhD/Datasets/5PI/Increasing_Load_1P3S"

[[datasets]]
name = "Reliability Impact"
exp_folders = "/Users/kaleem/PhD/Data/5PI/--_Reliability Impact/reliability_impact_100b_uc_0dur_ppss_raw"
ap_config = ""
dataset_path = "/Users/kaleem/PhD/Datasets/5PI/Reliability_Impact"

[[datasets]]
name = "QoS 1P3S"
exp_folders = "/Users/kaleem/PhD/Data/5PI/00_QoS Capture/QoS_1P3S"
ap_config = ""
dataset_path = "/Users/kaleem/PhD/Datasets/5PI/QoS_1P3S"

[[datasets]]
name = "QoS 2P2S"
exp_folders = "/Users/kaleem/PhD/Data/5PI/00_QoS Capture/QoS_2P2S"
ap_config = ""
dataset_path = "/Users/kaleem/PhD/Datasets/5PI/QoS_2P2S"

[[datasets]]
name = "QoS 3P1S"
exp_folders = "/Users/kaleem/PhD/Data/5PI/00_QoS Capture/QoS_3P1S"
ap_config = ""
dataset_path = "/Users/kaleem/PhD/Datasets/5PI/QoS_3P1S"

[[datasets]]
name = "Participant Threshold"
exp_folders = "/Users/kaleem/PhD/Data/5PI/01_Participant Threshold/Participant_Threshold"
ap_config = ""
dataset_path = "/Users/kaleem/PhD/Datasets/5PI/Participant_Threshold"

[[datasets]]
name = "Mcast 1P3S BW High"
exp_folders = "/Users/kaleem/PhD/Data/5PI/02_Multicast Exploration/Mcast_1P3S_BW_High"
ap_config = ""
dataset_path = "/Users/kaleem/PhD/Datasets/5PI/Mcast_1P3S_BW_High"

[[datasets]]
name = "Mcast 1P3S BW Low"
exp_folders = "/Users/kaleem/PhD/Data/5PI/02_Multicast Exploration/Mcast_1P3S_BW_Low"
ap_config = ""
dataset_path = "/Users/kaleem/PhD/Datasets/5PI/Mcast_1P3S_BW_Low"

[[datasets]]
name = "Mcast 1P3S BW Medium"
exp_folders = "/Users/kaleem/PhD/Data/5PI/02_Multicast Exploration/Mcast_1P3S_BW_Medium"
ap_config = ""
dataset_path = "/Users/kaleem/PhD/Datasets/5PI/Mcast_1P3S_BW_Medium"

[[datasets]]
name = "Mcast 1P3S No Noise"
exp_folders = "/Users/kaleem/PhD/Data/5PI/02_Multicast Exploration/Mcast_1P3S_No_Noise"
ap_config = ""
dataset_path = "/Users/kaleem/PhD/Datasets/5PI/Mcast_1P3S_No_Noise"

[[datasets]]
name = "Mcast 2P2S"
exp_folders = "/Users/kaleem/PhD/Data/5PI/02_Multicast Exploration/Mcast_2P2S"
ap_config = ""
dataset_path = "/Users/kaleem/PhD/Datasets/5PI/Mcast_2P2S"

[[datasets]]
name = "ML 24Mbps"
exp_folders = "/Users/kaleem/PhD/Data/5PI/04_Machine Learning Data Collection 24Mbps/ML_24Mbps"
ap_config = ""
dataset_path = "/Users/kaleem/PhD/Datasets/5PI/ML_24Mbps"

[[datasets]]
name = "ML 71Mbps"
exp_folders = "/Users/kaleem/PhD/Data/5PI/05_Machine Learning Data Collection 71Mbps/ML_71Mbps"
ap_config = ""
dataset_path = "/Users/kaleem/PhD/Datasets/5PI/ML_71Mbps"

# [[datasets]]
# name = ""
# exp_folders = ""
# ap_config = ""
# dataset_path = ""
